/**
 *  This file was auto generated, please do not edit it directly.
**/

package domaintype

type EFx struct {
}

func NewEFx() *EFx {
	return &EFx{}
}

type EFxModuleType struct {
	Id                    bool
	Slug                  string
	Name                  string
	Description           string
	IsAccessControl       bool
	IsActivation          bool
	IsConcierge           bool
	IsAthleteBag          bool
	IsDigitalMemoryBank   bool
	IsGuestInfo           bool
	IsMessaging           bool
	IsProductPickup       bool
	IsRaffle              bool
	IsReservation         bool
	IsRoamingPhotographer bool
	IsSmartBar            bool
	IsSmsQuiz             bool
	IsTeams               bool
	IsAdminOnly           bool
	IconURL               bool
	DependencyNFC         bool
	DependencySMS         bool
	CompatibilityNFC      bool
	CompatibilitySMS      bool
}

func (f *EFx) ListEFxModuleTypes() []EFxModuleType {
	return []EFxModuleType{
		{
			Id:                    `AccessControl`,
			Slug:                  `access-control`,
			Name:                  `Access Control`,
			Description:           `Scan credentials to grant access to exclusive event experiences`,
			IsAccessControl:       true,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Concierge`,
			Slug:                  `concierge`,
			Name:                  `Concierge`,
			Description:           `Deliver key information to attendees when they scan credentials at kiosks`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           true,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `DigitalMemoryBank`,
			Slug:                  `digital-memory-bank`,
			Name:                  `Digital Memory Bank`,
			Description:           `Deliver key information to attendees&#039; when they scan credentials at kiosks`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   true,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Messaging`,
			Slug:                  `messaging`,
			Name:                  `Messaging`,
			Description:           `Engage attendees through messages delivered over SMS`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           true,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         false,
			DependencySMS:         true,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `SMSQuiz`,
			Slug:                  `smsquiz`,
			Name:                  `Poll`,
			Description:           `Poll guests over SMS. View responses in-app or display on visualizers`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             true,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         false,
			DependencySMS:         true,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `ProductPickup`,
			Slug:                  `product-pickup`,
			Name:                  `Product Pickup`,
			Description:           `Scan tag to confirm attendees eligibility to receive or purchase products`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       true,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Raffle`,
			Slug:                  `raffle`,
			Name:                  `Raffle`,
			Description:           `Select prize winners by random drawing and notify attendees via SMS`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              true,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         true,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Reservation`,
			Slug:                  `reservation`,
			Name:                  `Reservation`,
			Description:           `Manage high-interest access points by queueing attendees in a virtual line`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         true,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `RoamingPhotographer`,
			Slug:                  `roaming-photographer`,
			Name:                  `Roaming Photographer`,
			Description:           `Take photos using custom event filters. Deliver images to attendees over SMS`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: true,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      true,
		},
		{
			Id:                    `Smart Bar`,
			Slug:                  `smart-bar`,
			Name:                  `Smart Bar`,
			Description:           `Receive and fill attendee orders placed by scanning credentials at bar kiosks`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            true,
			IsSmsQuiz:             false,
			IsTeams:               false,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         true,
			DependencySMS:         false,
			CompatibilityNFC:      true,
			CompatibilitySMS:      false,
		},
		{
			Id:                    `Teams`,
			Slug:                  `teams`,
			Name:                  `Teams `,
			Description:           `Build attendee teams for competition; track scores on the leaderboard`,
			IsAccessControl:       false,
			IsActivation:          false,
			IsConcierge:           false,
			IsAthleteBag:          false,
			IsDigitalMemoryBank:   false,
			IsGuestInfo:           false,
			IsMessaging:           false,
			IsProductPickup:       false,
			IsRaffle:              false,
			IsReservation:         false,
			IsRoamingPhotographer: false,
			IsSmartBar:            false,
			IsSmsQuiz:             false,
			IsTeams:               true,
			IsAdminOnly:           false,
			IconURL:               `https://firebasestorage.googleapis.com/v0/b/efx-production.appspot.com/o/Module%20Icons%2FAccess%20Control%20Icon.png?alt=media&amp;token=4d23a3f0-212a-4f23-8110-9e7a6fe791d8`,
			DependencyNFC:         false,
			DependencySMS:         false,
			CompatibilityNFC:      false,
			CompatibilitySMS:      true,
		},
	}
}
