/**
 *  This file was auto generated, please do not edit it directly.
**/

package domaintype

type Event struct {
}

func NewEvent() *Event {
	return &Event{}
}

type CIOMarketingEventCountType struct {
	Slug                   string
	Name                   string
	Description            string
	IsFewerThanFive        bool
	IsMoreThanThirty       bool
	IsBetweenFiveAndThirty bool
}

type CIOMarketingEventType struct {
	Slug                   string
	Name                   string
	Description            string
	IsBrandAwarenessEvents bool
	IsTradeShows           bool
	IsConferences          bool
	IsRoadshows            bool
	IsInternalMeetings     bool
	IsRecruitingEvents     bool
	IsFundraisingEvents    bool
}

type CIOMarketingIndustryType struct {
	Slug                     string
	Name                     string
	Description              string
	IsAgency                 bool
	IsEducation              bool
	IsFinance                bool
	IsSportsAndEntertainment bool
	IsTechnology             bool
	IsOther                  bool
}

type EventDateFilterType struct {
	Slug                   string
	Name                   string
	Description            string
	IsCurrentFuture        bool
	IsPastAll              bool
	IsPast3Months          bool
	IsPast3MonthsAndFuture bool
	IsPast6Months          bool
}

type EventMessageSlugType struct {
	Slug                      string
	Name                      string
	Description               string
	IsEventPublicURL          bool
	IsEventName               bool
	IsEventEmail              bool
	IsEventLocationName       bool
	IsEventLocationAddress    bool
	IsEventDescription        bool
	IsEventFacebook           bool
	IsEventTwitter            bool
	IsEventInstagram          bool
	IsEventStartDateTime      bool
	IsEventStartDate          bool
	IsEventStartTime          bool
	IsEventStartDateTimeShort bool
	IsEventStartDateShort     bool
	IsEventStartTimeShort     bool
	IsEventStartDateTimeLong  bool
	IsEventStartDateLong      bool
	IsEventStartTimeLong      bool
	IsEventEndDateTime        bool
	IsEventEndDate            bool
	IsEventEndTime            bool
	IsEventEndDateTimeShort   bool
	IsEventEndDateShort       bool
	IsEventEndTimeShort       bool
	IsEventEndDateTimeLong    bool
	IsEventEndDateLong        bool
	IsEventEndTimeLong        bool
}

type EventMessageType struct {
	Slug                  string
	Name                  string
	Description           string
	IsIntroduction        bool
	IsOpening             bool
	IsClosing             bool
	IsConfirmation        bool
	IsDeclination         bool
	IsSoldOut             bool
	IsReveal              bool
	IsDisclaimer          bool
	IsResponseRestriction bool
	DefaultValue          bool
	Value                 bool
}

type EventType struct {
	Slug        string
	Name        string
	Description string
	IsEventFarm bool
	IsCio       bool
	IsListly    bool
	IsDnc       bool
	IsRnc       bool
	IsRslc      bool
	IsSundance  bool
}

type MapSourceType struct {
	Slug        string
	Name        string
	Description string
	IsGoogle    bool
	IsYahoo     bool
	IsBing      bool
}

type QuestionContextType struct {
	Slug           string
	Name           string
	Description    string
	IsRegistration bool
	IsLeadCapture  bool
}

type QuestionType struct {
	Slug        string
	Name        string
	Description string
	IsCheckbox  bool
	IsRadio     bool
	IsMulti     bool
	IsText      bool
	IsSelect    bool
	IsDate      bool
	IsWaiver    bool
}

type ThemeColorType struct {
	Slug         string
	Name         string
	Description  string
	IsAlert      bool
	IsBackground bool
	IsFont       bool
	IsPrimary    bool
	IsPrimaryAlt bool
}

type ThemeFontFamilyType struct {
	Slug        string
	Name        string
	Description string
	IsTimes     bool
}

type ThemeNameType struct {
	Slug        string
	Name        string
	Description string
	IsMaterial  bool
}

type TrackingScriptType struct {
	Slug           string
	Name           string
	Description    string
	IsRegistration bool
	IsConfirmation bool
	Value          bool
}

func (f *Event) ListCIOMarketingEventCountTypes() []CIOMarketingEventCountType {
	return []CIOMarketingEventCountType{
		{
			Slug:                   `fewer-than-5`,
			Name:                   `Fewer than 5`,
			Description:            ``,
			IsFewerThanFive:        true,
			IsMoreThanThirty:       false,
			IsBetweenFiveAndThirty: false,
		},
		{
			Slug:                   `between-5-and-30`,
			Name:                   `Between 5 and 30`,
			Description:            ``,
			IsFewerThanFive:        false,
			IsMoreThanThirty:       false,
			IsBetweenFiveAndThirty: true,
		},
		{
			Slug:                   `more-than-30`,
			Name:                   `More than 30`,
			Description:            ``,
			IsFewerThanFive:        false,
			IsMoreThanThirty:       true,
			IsBetweenFiveAndThirty: false,
		},
	}
}

func (f *Event) ListCIOMarketingEventTypes() []CIOMarketingEventType {
	return []CIOMarketingEventType{
		{
			Slug:                   `brand-awareness-events`,
			Name:                   `Brand Awareness Events`,
			Description:            ``,
			IsBrandAwarenessEvents: true,
			IsTradeShows:           false,
			IsConferences:          false,
			IsRoadshows:            false,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `trade-shows`,
			Name:                   `Trade Shows`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           true,
			IsConferences:          false,
			IsRoadshows:            false,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `conferences`,
			Name:                   `Conferences`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           false,
			IsConferences:          true,
			IsRoadshows:            false,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `roadshows`,
			Name:                   `Roadshows`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           false,
			IsConferences:          false,
			IsRoadshows:            true,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `internal-meetings`,
			Name:                   `Internal Meetings`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           false,
			IsConferences:          false,
			IsRoadshows:            false,
			IsInternalMeetings:     true,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `recruiting-events`,
			Name:                   `Recruiting Events`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           false,
			IsConferences:          false,
			IsRoadshows:            false,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     true,
			IsFundraisingEvents:    false,
		},
		{
			Slug:                   `fundraising-events`,
			Name:                   `Fundraising Events`,
			Description:            ``,
			IsBrandAwarenessEvents: false,
			IsTradeShows:           false,
			IsConferences:          false,
			IsRoadshows:            false,
			IsInternalMeetings:     false,
			IsRecruitingEvents:     false,
			IsFundraisingEvents:    true,
		},
	}
}

func (f *Event) ListCIOMarketingIndustryTypes() []CIOMarketingIndustryType {
	return []CIOMarketingIndustryType{
		{
			Slug:                     `consumer-goods`,
			Name:                     `Consumer Goods`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              false,
			IsFinance:                false,
			IsSportsAndEntertainment: false,
			IsTechnology:             false,
			IsOther:                  false,
		},
		{
			Slug:                     `agency`,
			Name:                     `Agency`,
			Description:              ``,
			IsAgency:                 true,
			IsEducation:              false,
			IsFinance:                false,
			IsSportsAndEntertainment: false,
			IsTechnology:             false,
			IsOther:                  false,
		},
		{
			Slug:                     `education`,
			Name:                     `Education`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              true,
			IsFinance:                false,
			IsSportsAndEntertainment: false,
			IsTechnology:             false,
			IsOther:                  false,
		},
		{
			Slug:                     `finance`,
			Name:                     `Finance`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              false,
			IsFinance:                true,
			IsSportsAndEntertainment: false,
			IsTechnology:             false,
			IsOther:                  false,
		},
		{
			Slug:                     `sports-and-entertainment`,
			Name:                     `Sports and Entertainment`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              false,
			IsFinance:                false,
			IsSportsAndEntertainment: true,
			IsTechnology:             false,
			IsOther:                  false,
		},
		{
			Slug:                     `technology`,
			Name:                     `Technology`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              false,
			IsFinance:                false,
			IsSportsAndEntertainment: false,
			IsTechnology:             true,
			IsOther:                  false,
		},
		{
			Slug:                     `other`,
			Name:                     `Other`,
			Description:              ``,
			IsAgency:                 false,
			IsEducation:              false,
			IsFinance:                false,
			IsSportsAndEntertainment: false,
			IsTechnology:             false,
			IsOther:                  true,
		},
	}
}

func (f *Event) ListEventDateFilterTypes() []EventDateFilterType {
	return []EventDateFilterType{
		{
			Slug:                   `current-future`,
			Name:                   `Current &amp; Future Events`,
			Description:            `This will show you all your future and current events.`,
			IsCurrentFuture:        true,
			IsPastAll:              false,
			IsPast3Months:          false,
			IsPast3MonthsAndFuture: false,
			IsPast6Months:          false,
		},
		{
			Slug:                   `past-all`,
			Name:                   `All Past Events`,
			Description:            ``,
			IsCurrentFuture:        false,
			IsPastAll:              true,
			IsPast3Months:          false,
			IsPast3MonthsAndFuture: false,
			IsPast6Months:          false,
		},
		{
			Slug:                   `past-3-months`,
			Name:                   `Past 3 Months`,
			Description:            ``,
			IsCurrentFuture:        false,
			IsPastAll:              false,
			IsPast3Months:          true,
			IsPast3MonthsAndFuture: false,
			IsPast6Months:          false,
		},
		{
			Slug:                   `past-3-months-and-future`,
			Name:                   `Past 3 Months and Future Events`,
			Description:            `This will show you past 3 months events and all future events`,
			IsCurrentFuture:        false,
			IsPastAll:              false,
			IsPast3Months:          false,
			IsPast3MonthsAndFuture: true,
			IsPast6Months:          false,
		},
		{
			Slug:                   `past-6-months`,
			Name:                   `Past 6 Months`,
			Description:            ``,
			IsCurrentFuture:        false,
			IsPastAll:              false,
			IsPast3Months:          false,
			IsPast3MonthsAndFuture: false,
			IsPast6Months:          true,
		},
	}
}

func (f *Event) ListEventMessageSlugTypes() []EventMessageSlugType {
	return []EventMessageSlugType{
		{
			Slug:                      `{{eventPublicUrl}}`,
			Name:                      `Event Public URL`,
			Description:               ``,
			IsEventPublicURL:          true,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventName}}`,
			Name:                      `Event Name`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               true,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEmail}}`,
			Name:                      `Event Email`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              true,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventLocationName}}`,
			Name:                      `Event Location Name`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       true,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventLocationAddress}}`,
			Name:                      `Event Location Address`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    true,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventDescription}}`,
			Name:                      `Event Description`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        true,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventFacebook}}`,
			Name:                      `Event Facebook`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           true,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventTwitter}}`,
			Name:                      `Event Twitter`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            true,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventInstagram}}`,
			Name:                      `Event Instagram`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          true,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateTime}}`,
			Name:                      `Event Start Date - Time`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      true,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDate}}`,
			Name:                      `Event Start Date`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          true,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartTime}}`,
			Name:                      `Event Start Time`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          true,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateTimeShort}}`,
			Name:                      `Event Start Date - Time (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: true,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateShort}}`,
			Name:                      `Event Start Date (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     true,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateShort}}`,
			Name:                      `Event Start Date (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     true,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateTimeLong}}`,
			Name:                      `Event Start Date - Time (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  true,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartDateLong}}`,
			Name:                      `Event Start Date (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      true,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventStartTimeLong}}`,
			Name:                      `Event Start Time (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      true,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDateTime}}`,
			Name:                      `Event End Date - Time`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        true,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDate}}`,
			Name:                      `Event End Date`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            true,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndTime}}`,
			Name:                      `Event End Time`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            true,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDateTimeShort}}`,
			Name:                      `Event End Date - Time (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   true,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDateShort}}`,
			Name:                      `Event End Date (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       true,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndTimeShort}}`,
			Name:                      `Event End Time (Short)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       true,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDateTimeLong}}`,
			Name:                      `Event End Date - Time (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    true,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndDateLong}}`,
			Name:                      `Event End Date (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        true,
			IsEventEndTimeLong:        false,
		},
		{
			Slug:                      `{{eventEndTimeLong}}`,
			Name:                      `Event End Time (Long)`,
			Description:               ``,
			IsEventPublicURL:          false,
			IsEventName:               false,
			IsEventEmail:              false,
			IsEventLocationName:       false,
			IsEventLocationAddress:    false,
			IsEventDescription:        false,
			IsEventFacebook:           false,
			IsEventTwitter:            false,
			IsEventInstagram:          false,
			IsEventStartDateTime:      false,
			IsEventStartDate:          false,
			IsEventStartTime:          false,
			IsEventStartDateTimeShort: false,
			IsEventStartDateShort:     false,
			IsEventStartTimeShort:     false,
			IsEventStartDateTimeLong:  false,
			IsEventStartDateLong:      false,
			IsEventStartTimeLong:      false,
			IsEventEndDateTime:        false,
			IsEventEndDate:            false,
			IsEventEndTime:            false,
			IsEventEndDateTimeShort:   false,
			IsEventEndDateShort:       false,
			IsEventEndTimeShort:       false,
			IsEventEndDateTimeLong:    false,
			IsEventEndDateLong:        false,
			IsEventEndTimeLong:        true,
		},
	}
}

func (f *Event) ListEventMessageTypes() []EventMessageType {
	return []EventMessageType{
		{
			Slug:                  `additional`,
			Name:                  `Registration Introduction`,
			Description:           `Displayed to guests at the beginning of the purchase/registration/RSVP process.`,
			IsIntroduction:        true,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          ``,
			Value:                 ``,
		},
		{
			Slug:                  `before-opening`,
			Name:                  `Prior To Opening`,
			Description:           `Displayed as a placeholder for the registration or purchase form before the event goes live and tickets become available.`,
			IsIntroduction:        false,
			IsOpening:             true,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          `Tickets for {{eventName}} are not yet available—please check back in the near future!`,
			Value:                 ``,
		},
		{
			Slug:                  `after-closing`,
			Name:                  `After Closing`,
			Description:           `Displayed as a placeholder for the registration or purchase form once registration has closed for an event.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             true,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          `Tickets for {{eventName}} are no longer available through this website. Please check with the event organizers to find out if tickets are available elsewhere.`,
			Value:                 ``,
		},
		{
			Slug:                  `confirmation`,
			Name:                  `Confirmation`,
			Description:           `Displayed on the confirmation screen after a successful purchase, registration or RSVP.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        true,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          `You&#039;re all set. We look forward to seeing you soon!`,
			Value:                 ``,
		},
		{
			Slug:                  `declination`,
			Name:                  `Declination`,
			Description:           `Displayed on the confirmation screen after a guest declines their RSVP.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         true,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          `Thanks for your response. We&#039;re sorry we&#039;ll miss you!`,
			Value:                 ``,
		},
		{
			Slug:                  `sold-out`,
			Name:                  `Sold-Out`,
			Description:           `Displayed for any event access type (General Admission, VIP, etc.) that is either sold out or at capacity.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             true,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          ``,
			Value:                 ``,
		},
		{
			Slug:                  `reveal`,
			Name:                  `Reveal`,
			Description:           `If Invitation Reveal is enabled, the &quot;Reveal Message&quot; will display when a guest begins the registration process.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              true,
			IsDisclaimer:          false,
			IsResponseRestriction: false,
			DefaultValue:          `Tickets for {{eventName}} are no longer available. If you feel you have reached this page in error, please contact the event organizers for more information.`,
			Value:                 ``,
		},
		{
			Slug:                  `disclaimer`,
			Name:                  `Disclaimer`,
			Description:           `If you have created a Waiver question, this message will display as part of the purchase, registration, and RSVP process. The guest must check the disclaimer box to complete registration.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          true,
			IsResponseRestriction: false,
			DefaultValue:          ``,
			Value:                 ``,
		},
		{
			Slug:                  `response-restriction`,
			Name:                  `Response Restriction`,
			Description:           `If the Event Setting “Guest can change response” is “NO”, this message will display for any registered guest who clicks the invitation link again.`,
			IsIntroduction:        false,
			IsOpening:             false,
			IsClosing:             false,
			IsConfirmation:        false,
			IsDeclination:         false,
			IsSoldOut:             false,
			IsReveal:              false,
			IsDisclaimer:          false,
			IsResponseRestriction: true,
			DefaultValue:          ``,
			Value:                 ``,
		},
	}
}

func (f *Event) ListEventTypes() []EventType {
	return []EventType{
		{
			Slug:        `eventfarm`,
			Name:        `Event Farm`,
			Description: ``,
			IsEventFarm: true,
			IsCio:       false,
			IsListly:    false,
			IsDnc:       false,
			IsRnc:       false,
			IsRslc:      false,
			IsSundance:  false,
		},
		{
			Slug:        `cio`,
			Name:        `Check-in-Only`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       true,
			IsListly:    false,
			IsDnc:       false,
			IsRnc:       false,
			IsRslc:      false,
			IsSundance:  false,
		},
		{
			Slug:        `listly`,
			Name:        `Listly`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       false,
			IsListly:    true,
			IsDnc:       false,
			IsRnc:       false,
			IsRslc:      false,
			IsSundance:  false,
		},
		{
			Slug:        `dnc`,
			Name:        `DNC`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       false,
			IsListly:    false,
			IsDnc:       true,
			IsRnc:       false,
			IsRslc:      false,
			IsSundance:  false,
		},
		{
			Slug:        `rnc`,
			Name:        `RNC`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       false,
			IsListly:    false,
			IsDnc:       false,
			IsRnc:       true,
			IsRslc:      false,
			IsSundance:  false,
		},
		{
			Slug:        `rslc`,
			Name:        `RSLC`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       false,
			IsListly:    false,
			IsDnc:       false,
			IsRnc:       false,
			IsRslc:      true,
			IsSundance:  false,
		},
		{
			Slug:        `sundance`,
			Name:        `Sundance`,
			Description: ``,
			IsEventFarm: false,
			IsCio:       false,
			IsListly:    false,
			IsDnc:       false,
			IsRnc:       false,
			IsRslc:      false,
			IsSundance:  true,
		},
	}
}

func (f *Event) ListMapSourceTypes() []MapSourceType {
	return []MapSourceType{
		{
			Slug:        `google`,
			Name:        `Google`,
			Description: `Google Maps`,
			IsGoogle:    true,
			IsYahoo:     false,
			IsBing:      false,
		},
		{
			Slug:        `yahoo`,
			Name:        `Yahoo`,
			Description: `Yahoo Maps`,
			IsGoogle:    false,
			IsYahoo:     true,
			IsBing:      false,
		},
		{
			Slug:        `bing`,
			Name:        `Bing`,
			Description: `Bing Maps`,
			IsGoogle:    false,
			IsYahoo:     false,
			IsBing:      true,
		},
	}
}

func (f *Event) ListQuestionContextTypes() []QuestionContextType {
	return []QuestionContextType{
		{
			Slug:           `registration`,
			Name:           `Registration`,
			Description:    ``,
			IsRegistration: true,
			IsLeadCapture:  false,
		},
		{
			Slug:           `lead`,
			Name:           `Lead Capture`,
			Description:    ``,
			IsRegistration: false,
			IsLeadCapture:  true,
		},
	}
}

func (f *Event) ListQuestionTypes() []QuestionType {
	return []QuestionType{
		{
			Slug:        `checkbox`,
			Name:        `Checkbox`,
			Description: ``,
			IsCheckbox:  true,
			IsRadio:     false,
			IsMulti:     false,
			IsText:      false,
			IsSelect:    false,
			IsDate:      false,
			IsWaiver:    false,
		},
		{
			Slug:        `radio`,
			Name:        `Radio`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     true,
			IsMulti:     false,
			IsText:      false,
			IsSelect:    false,
			IsDate:      false,
			IsWaiver:    false,
		},
		{
			Slug:        `multi`,
			Name:        `Multi`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     false,
			IsMulti:     true,
			IsText:      false,
			IsSelect:    false,
			IsDate:      false,
			IsWaiver:    false,
		},
		{
			Slug:        `text`,
			Name:        `Text`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     false,
			IsMulti:     false,
			IsText:      true,
			IsSelect:    false,
			IsDate:      false,
			IsWaiver:    false,
		},
		{
			Slug:        `select`,
			Name:        `Select`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     false,
			IsMulti:     false,
			IsText:      false,
			IsSelect:    true,
			IsDate:      false,
			IsWaiver:    false,
		},
		{
			Slug:        `date`,
			Name:        `Date`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     false,
			IsMulti:     false,
			IsText:      false,
			IsSelect:    false,
			IsDate:      true,
			IsWaiver:    false,
		},
		{
			Slug:        `waiver`,
			Name:        `Waiver`,
			Description: ``,
			IsCheckbox:  false,
			IsRadio:     false,
			IsMulti:     false,
			IsText:      false,
			IsSelect:    false,
			IsDate:      false,
			IsWaiver:    true,
		},
	}
}

func (f *Event) ListThemeColorTypes() []ThemeColorType {
	return []ThemeColorType{
		{
			Slug:         `alert`,
			Name:         `Alert Color`,
			Description:  `#df260a`,
			IsAlert:      true,
			IsBackground: false,
			IsFont:       false,
			IsPrimary:    false,
			IsPrimaryAlt: false,
		},
		{
			Slug:         `background`,
			Name:         `Background Color`,
			Description:  `#ffffff`,
			IsAlert:      false,
			IsBackground: true,
			IsFont:       false,
			IsPrimary:    false,
			IsPrimaryAlt: false,
		},
		{
			Slug:         `font`,
			Name:         `Font Color`,
			Description:  `#444444`,
			IsAlert:      false,
			IsBackground: false,
			IsFont:       true,
			IsPrimary:    false,
			IsPrimaryAlt: false,
		},
		{
			Slug:         `primary`,
			Name:         `Primary Color`,
			Description:  `#5085F0`,
			IsAlert:      false,
			IsBackground: false,
			IsFont:       false,
			IsPrimary:    true,
			IsPrimaryAlt: false,
		},
		{
			Slug:         `primaryAlt`,
			Name:         `Primary Alt Color`,
			Description:  `#A2AEBB`,
			IsAlert:      false,
			IsBackground: false,
			IsFont:       false,
			IsPrimary:    false,
			IsPrimaryAlt: true,
		},
	}
}

func (f *Event) ListThemeFontFamilyTypes() []ThemeFontFamilyType {
	return []ThemeFontFamilyType{
		{
			Slug:        `times`,
			Name:        `Times New Roman`,
			Description: ``,
			IsTimes:     true,
		},
	}
}

func (f *Event) ListThemeNameTypes() []ThemeNameType {
	return []ThemeNameType{
		{
			Slug:        `material`,
			Name:        `Material Design`,
			Description: ``,
			IsMaterial:  true,
		},
	}
}

func (f *Event) ListTrackingScriptTypes() []TrackingScriptType {
	return []TrackingScriptType{
		{
			Slug:           `registration_tracking_script`,
			Name:           `Registration Tracking Script`,
			Description:    `Provide the tracking script for your analytics tool, such as Google Analytics, to collect data on visitors to the registration form.`,
			IsRegistration: true,
			IsConfirmation: false,
			Value:          ``,
		},
		{
			Slug:           `confirmation_tracking_script`,
			Name:           `Confirmation Tracking Script`,
			Description:    `Provide the tracking script for your analytics tool, such as Google Analytics, to collect data on visitors to the confirmation page.`,
			IsRegistration: false,
			IsConfirmation: true,
			Value:          ``,
		},
	}
}
