/**
 *  This file was auto generated, please do not edit it directly.
**/

package domaintype

type User struct {
}

func NewUser() *User {
	return &User{}
}

type EventRoleType struct {
	Slug           string
	Name           string
	Description    string
	IsOrganizer    bool
	IsAssistant    bool
	IsSupport      bool
	IsCheckInStaff bool
	IsReadOnly     bool
}

type ProviderType struct {
	Slug         string
	Name         string
	Description  string
	IsGoogle     bool
	IsMarketo    bool
	IsLinkedIn   bool
	IsSalesforce bool
}

type RoleType struct {
	Slug               string
	Name               string
	Description        string
	IsNone             bool
	IsUser             bool
	IsAdmin            bool
	IsEventCrud        bool
	IsEventView        bool
	IsTicketBlockCrud  bool
	IsTicketBlockView  bool
	IsAddressBookCrud  bool
	IsAddressBookView  bool
	IsUserCrud         bool
	IsUserView         bool
	IsListView         bool
	IsListCrud         bool
	IsUpload           bool
	IsEmail            bool
	IsReports          bool
	IsMassRemove       bool
	IsCustomLayout     bool
	IsPayments         bool
	IsWillCall         bool
	IsPartner          bool
	IsInventoryRecords bool
	IsContestScores    bool
	IsPoolContact      bool
}

type TokenStateType struct {
	Slug        string
	Name        string
	Description string
	IsSuccess   bool
	IsFailure   bool
	IsUnknown   bool
}

type UserAttributeNamespaceType struct {
	Slug         string
	Name         string
	Description  string
	IsInternal   bool
	IsInfo       bool
	IsHover      bool
	IsSpamReport bool
	IsLinkedin   bool
	IsSalesforce bool
	IsTwitter    bool
	IsConvio     bool
	IsGoogle     bool
	IsCustom     bool
}

type UserIdentifierType struct {
	Slug        string
	Name        string
	Description string
	IsEmail     bool
	IsIpad      bool
	IsSfLead    bool
	IsSfContact bool
}

type UserPermissionType struct {
	Slug        string
	Name        string
	Description string
	IsGroup     bool
}

type UserRoleType struct {
	Slug           string
	Name           string
	Description    string
	IsGlobal       bool
	IsEvents       bool
	IsTicketblocks bool
	IsPools        bool
}

func (f *User) ListEventRoleTypes() []EventRoleType {
	return []EventRoleType{
		{
			Slug:           `organizer`,
			Name:           `Organizer`,
			Description:    `An Organizer has read and write access to all event related features.`,
			IsOrganizer:    true,
			IsAssistant:    false,
			IsSupport:      false,
			IsCheckInStaff: false,
			IsReadOnly:     false,
		},
		{
			Slug:           `assistant`,
			Name:           `Assistant`,
			Description:    `An Assistant can view event settings, manage the guest list, handle check-ins and view reports.`,
			IsOrganizer:    false,
			IsAssistant:    true,
			IsSupport:      false,
			IsCheckInStaff: false,
			IsReadOnly:     false,
		},
		{
			Slug:           `support`,
			Name:           `Support`,
			Description:    `Support can view event details, manage guest lists, and handle check-ins.`,
			IsOrganizer:    false,
			IsAssistant:    false,
			IsSupport:      true,
			IsCheckInStaff: false,
			IsReadOnly:     false,
		},
		{
			Slug:           `check-in-staff`,
			Name:           `Check In Staff`,
			Description:    `Check In Staff can view event details, the guest list, and can check guests in.`,
			IsOrganizer:    false,
			IsAssistant:    false,
			IsSupport:      false,
			IsCheckInStaff: true,
			IsReadOnly:     false,
		},
		{
			Slug:           `read-only`,
			Name:           `Read Only`,
			Description:    `Read Only can only view event details.`,
			IsOrganizer:    false,
			IsAssistant:    false,
			IsSupport:      false,
			IsCheckInStaff: false,
			IsReadOnly:     true,
		},
	}
}

func (f *User) ListProviderTypes() []ProviderType {
	return []ProviderType{
		{
			Slug:         `google`,
			Name:         `Google`,
			Description:  ``,
			IsGoogle:     true,
			IsMarketo:    false,
			IsLinkedIn:   false,
			IsSalesforce: false,
		},
		{
			Slug:         `marketo`,
			Name:         `Marketo`,
			Description:  ``,
			IsGoogle:     false,
			IsMarketo:    true,
			IsLinkedIn:   false,
			IsSalesforce: false,
		},
		{
			Slug:         `linked_in`,
			Name:         `Linked In`,
			Description:  ``,
			IsGoogle:     false,
			IsMarketo:    false,
			IsLinkedIn:   true,
			IsSalesforce: false,
		},
		{
			Slug:         `salesforce`,
			Name:         `Salesforce`,
			Description:  ``,
			IsGoogle:     false,
			IsMarketo:    false,
			IsLinkedIn:   false,
			IsSalesforce: true,
		},
	}
}

func (f *User) ListRoleTypes() []RoleType {
	return []RoleType{
		{
			Slug:               `none`,
			Name:               `None`,
			Description:        ``,
			IsNone:             true,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `user`,
			Name:               `User`,
			Description:        ``,
			IsNone:             false,
			IsUser:             true,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `admin`,
			Name:               `Admin`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            true,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `event-crud`,
			Name:               `Event CRUD`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        true,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `event-view`,
			Name:               `Event View`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        true,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `ticket-block-crud`,
			Name:               `TicketBlock CRUD`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  true,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `ticket-block-view`,
			Name:               `TicketBlock View`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  true,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `address-book-crud`,
			Name:               `Address Book CRUD`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  true,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `address-book-view`,
			Name:               `Address Book View`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  true,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `user-crud`,
			Name:               `User CRUD`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         true,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `user-view`,
			Name:               `User View`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         true,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `list-view`,
			Name:               `List View`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         true,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `list-crud`,
			Name:               `List CRUD`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         true,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `upload`,
			Name:               `Upload`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           true,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `email`,
			Name:               `Email`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            true,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `reports`,
			Name:               `Reports`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          true,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `mass-remove`,
			Name:               `Mass Remove`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       true,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `custom-layout`,
			Name:               `Custom Layout`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     true,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `payments`,
			Name:               `Payments`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         true,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `will-call`,
			Name:               `Will Call`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         true,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `partner`,
			Name:               `Partner`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          true,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `inventory-records`,
			Name:               `Inventory Records`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: true,
			IsContestScores:    false,
			IsPoolContact:      false,
		},
		{
			Slug:               `contest-scores`,
			Name:               `Contest Scores`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    true,
			IsPoolContact:      false,
		},
		{
			Slug:               `pool-contact`,
			Name:               `Pool Contact`,
			Description:        ``,
			IsNone:             false,
			IsUser:             false,
			IsAdmin:            false,
			IsEventCrud:        false,
			IsEventView:        false,
			IsTicketBlockCrud:  false,
			IsTicketBlockView:  false,
			IsAddressBookCrud:  false,
			IsAddressBookView:  false,
			IsUserCrud:         false,
			IsUserView:         false,
			IsListView:         false,
			IsListCrud:         false,
			IsUpload:           false,
			IsEmail:            false,
			IsReports:          false,
			IsMassRemove:       false,
			IsCustomLayout:     false,
			IsPayments:         false,
			IsWillCall:         false,
			IsPartner:          false,
			IsInventoryRecords: false,
			IsContestScores:    false,
			IsPoolContact:      true,
		},
	}
}

func (f *User) ListTokenStateTypes() []TokenStateType {
	return []TokenStateType{
		{
			Slug:        `success`,
			Name:        `Success`,
			Description: ``,
			IsSuccess:   true,
			IsFailure:   false,
			IsUnknown:   false,
		},
		{
			Slug:        `failure`,
			Name:        `Failure`,
			Description: ``,
			IsSuccess:   false,
			IsFailure:   true,
			IsUnknown:   false,
		},
		{
			Slug:        `unknown`,
			Name:        `Unknown`,
			Description: ``,
			IsSuccess:   false,
			IsFailure:   false,
			IsUnknown:   true,
		},
	}
}

func (f *User) ListUserAttributeNamespaceTypes() []UserAttributeNamespaceType {
	return []UserAttributeNamespaceType{
		{
			Slug:         `internal`,
			Name:         `Internal`,
			Description:  ``,
			IsInternal:   true,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `info`,
			Name:         `Info`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       true,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `hover`,
			Name:         `Hover`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      true,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `facebook`,
			Name:         `Facebook`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: true,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `linked-in`,
			Name:         `Linked In`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   true,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `salesforce`,
			Name:         `Salesforce`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: true,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `twitter`,
			Name:         `Twitter`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    true,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `convio`,
			Name:         `Convio`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     true,
			IsGoogle:     false,
			IsCustom:     false,
		},
		{
			Slug:         `google`,
			Name:         `Google`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     true,
			IsCustom:     false,
		},
		{
			Slug:         `custom`,
			Name:         `Custom`,
			Description:  ``,
			IsInternal:   false,
			IsInfo:       false,
			IsHover:      false,
			IsSpamReport: false,
			IsLinkedin:   false,
			IsSalesforce: false,
			IsTwitter:    false,
			IsConvio:     false,
			IsGoogle:     false,
			IsCustom:     true,
		},
	}
}

func (f *User) ListUserIdentifierTypes() []UserIdentifierType {
	return []UserIdentifierType{
		{
			Slug:        `email`,
			Name:        `Email`,
			Description: ``,
			IsEmail:     true,
			IsIpad:      false,
			IsSfLead:    false,
			IsSfContact: false,
		},
		{
			Slug:        `ipad`,
			Name:        `iPad`,
			Description: ``,
			IsEmail:     false,
			IsIpad:      true,
			IsSfLead:    false,
			IsSfContact: false,
		},
		{
			Slug:        `salesforce-lead`,
			Name:        `Salesforce Lead`,
			Description: ``,
			IsEmail:     false,
			IsIpad:      false,
			IsSfLead:    true,
			IsSfContact: false,
		},
		{
			Slug:        `salesforce-contact`,
			Name:        `Salesforce Contact`,
			Description: ``,
			IsEmail:     false,
			IsIpad:      false,
			IsSfLead:    false,
			IsSfContact: true,
		},
	}
}

func (f *User) ListUserPermissionTypes() []UserPermissionType {
	return []UserPermissionType{
		{
			Slug:        `group`,
			Name:        `Group`,
			Description: ``,
			IsGroup:     true,
		},
	}
}

func (f *User) ListUserRoleTypes() []UserRoleType {
	return []UserRoleType{
		{
			Slug:           `global`,
			Name:           `Global`,
			Description:    ``,
			IsGlobal:       true,
			IsEvents:       false,
			IsTicketblocks: false,
			IsPools:        false,
		},
		{
			Slug:           `events`,
			Name:           `Events`,
			Description:    ``,
			IsGlobal:       false,
			IsEvents:       true,
			IsTicketblocks: false,
			IsPools:        false,
		},
		{
			Slug:           `ticketblocks`,
			Name:           `TicketBlocks`,
			Description:    ``,
			IsGlobal:       false,
			IsEvents:       false,
			IsTicketblocks: true,
			IsPools:        false,
		},
		{
			Slug:           `pools`,
			Name:           `Pools`,
			Description:    ``,
			IsGlobal:       false,
			IsEvents:       false,
			IsTicketblocks: false,
			IsPools:        true,
		},
	}
}
